### ISSUE TITLE
QR code missing last line, even when scrolling down, with a full profile

### ISSUE THREAD

**Issue by axelsimon** [characterdog/share-my-number#12]
Running on Android 5.1

I filled in a complete work profile, but when I display it the last line of the QR code is missing, even if I manually scroll down. This probably isn't a problem, as QR codes have built-in error correction, but it doesn't look very nice.

It would probably be a good idea to scale down the QR code if it can't fit in the screen when there is too much info in the profile fields and maybe make it possible to tap the QR to display it full screen.

Cheers

**Comment by characterdog** [comment]
I cannot reproduce, but I increased the margin under the qr code: https://github.com/characterdog/share-my-number/commit/9f15a1aa826e57520bd94f5305d231cb7a73f50f

**Comment by axelsimon** [comment]
I got an updated version from F-Droid which I assumes contains the fix, and it makes a difference. Cool, thanks!

**Comment by characterdog** [comment]
You're welcome!
